#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

/**
 * TSP hook 事件到 OpenCode 事件的映射
 */
const EVENT_MAPPING = {
  'PreToolUse': 'tool.execute.before',
  'PostToolUse': 'tool.execute.after',
  'SessionStart': 'session.created',
  'Stop': 'session.idle',
};

/**
 * 工具名称映射
 */
const TOOL_MAPPING = {
  'Bash': 'bash',
  'Write': 'write',
  'Edit': 'edit',
  'MultiEdit': 'edit',
  'Read': 'read',
  'Grep': 'grep',
  'Glob': 'glob',
};

/**
 * 读取 hooks.json 配置
 */
function readHooksConfig(hooksDir) {
  const hooksConfigPath = path.join(hooksDir, 'hooks.json');
  if (!fs.existsSync(hooksConfigPath)) {
    return { hooks: {} };
  }

  try {
    return JSON.parse(fs.readFileSync(hooksConfigPath, 'utf8'));
  } catch (error) {
    console.warn(`Warning: Could not parse hooks.json: ${error.message}`);
    return { hooks: {} };
  }
}

/**
 * 转换单个 hook 配置
 */
function convertHookEntry(hookEntry, pluginRoot) {
  if (!hookEntry || typeof hookEntry !== 'object') {
    return null;
  }

  const { matcher, hooks, description, id } = hookEntry;

  if (!Array.isArray(hooks) || hooks.length === 0) {
    return null;
  }

  // 转换 matcher 为 OpenCode 工具过滤器
  const toolFilter = matcher === '*' ? null : matcher.split('|').map(tool => TOOL_MAPPING[tool] || tool.toLowerCase());

  // 转换 hooks 为 OpenCode 格式
  const convertedHooks = hooks.map(hook => {
    if (!hook || typeof hook !== 'object') {
      return null;
    }

    const { type, command, timeout, async: isAsync } = hook;

    if (type !== 'command' || !command) {
      return null;
    }

    // 替换变量
    const convertedCommand = command
      .replace(/\$\{CLAUDE_PLUGIN_ROOT\}/g, pluginRoot)
      .replace(/\$\{OPENCODE_PLUGIN_ROOT\}/g, pluginRoot);

    return {
      command: convertedCommand,
      timeout: timeout || 30,
      async: isAsync || false,
    };
  }).filter(Boolean);

  if (convertedHooks.length === 0) {
    return null;
  }

  return {
    id: id || `hook-${Date.now()}`,
    description: description || '',
    tools: toolFilter,
    hooks: convertedHooks,
  };
}

/**
 * 生成 OpenCode 插件代码
 */
function generatePluginCode(hooksConfig, pluginRoot) {
  const lines = [];

  lines.push('// TSP Hooks Plugin for OpenCode');
  lines.push('// Auto-generated by convert-hooks.js');
  lines.push('');
  lines.push('module.exports = function tspHooks({ project, directory, worktree, client, $ }) {');
  lines.push('  return {');

  // 转换 PreToolUse hooks
  const preToolUseHooks = (hooksConfig.hooks.PreToolUse || [])
    .map(entry => convertHookEntry(entry, pluginRoot))
    .filter(Boolean);

  if (preToolUseHooks.length > 0) {
    lines.push("    'tool.execute.before': async (input, output) => {");
    lines.push('      const toolName = input.tool;');
    lines.push('      const args = input.args;');
    lines.push('');

    for (const hook of preToolUseHooks) {
      const toolCondition = hook.tools
        ? ` && [${hook.tools.map(t => `'${t}'`).join(', ')}].includes(toolName)`
        : '';

      lines.push(`      // ${hook.description || hook.id}`);
      lines.push(`      if (true${toolCondition}) {`);
      lines.push(`        try {`);
      lines.push(`          const { execSync } = require('child_process');`);
      lines.push(`          const command = \`${hook.hooks[0].command.replace(/`/g, '\\`')}\`;`);
      lines.push(`          execSync(command, { timeout: ${hook.hooks[0].timeout * 1000}, cwd: directory });`);
      lines.push(`        } catch (error) {`);
      lines.push(`          // Hook failed, continue execution`);
      lines.push(`        }`);
      lines.push(`      }`);
      lines.push('');
    }

    lines.push('    },');
  }

  // 转换 PostToolUse hooks
  const postToolUseHooks = (hooksConfig.hooks.PostToolUse || [])
    .map(entry => convertHookEntry(entry, pluginRoot))
    .filter(Boolean);

  if (postToolUseHooks.length > 0) {
    lines.push("    'tool.execute.after': async (input, output) => {");
    lines.push('      const toolName = input.tool;');
    lines.push('      const args = input.args;');
    lines.push('      const result = output;');
    lines.push('');

    for (const hook of postToolUseHooks) {
      const toolCondition = hook.tools
        ? ` && [${hook.tools.map(t => `'${t}'`).join(', ')}].includes(toolName)`
        : '';

      lines.push(`      // ${hook.description || hook.id}`);
      lines.push(`      if (true${toolCondition}) {`);
      lines.push(`        try {`);
      lines.push(`          const { execSync } = require('child_process');`);
      lines.push(`          const command = \`${hook.hooks[0].command.replace(/`/g, '\\`')}\`;`);
      lines.push(`          execSync(command, { timeout: ${hook.hooks[0].timeout * 1000}, cwd: directory });`);
      lines.push(`        } catch (error) {`);
      lines.push(`          // Hook failed, continue execution`);
      lines.push(`        }`);
      lines.push(`      }`);
      lines.push('');
    }

    lines.push('    },');
  }

  // 转换 SessionStart hooks
  const sessionStartHooks = (hooksConfig.hooks.SessionStart || [])
    .map(entry => convertHookEntry(entry, pluginRoot))
    .filter(Boolean);

  if (sessionStartHooks.length > 0) {
    lines.push("    'session.created': async (input, output) => {");
    lines.push('');

    for (const hook of sessionStartHooks) {
      lines.push(`      // ${hook.description || hook.id}`);
      lines.push(`      try {`);
      lines.push(`        const { execSync } = require('child_process');`);
      lines.push(`        const command = \`${hook.hooks[0].command.replace(/`/g, '\\`')}\`;`);
      lines.push(`        execSync(command, { timeout: ${hook.hooks[0].timeout * 1000}, cwd: directory });`);
      lines.push(`      } catch (error) {`);
      lines.push(`        // Hook failed, continue execution`);
      lines.push(`      }`);
      lines.push('');
    }

    lines.push('    },');
  }

  // 转换 Stop hooks
  const stopHooks = (hooksConfig.hooks.Stop || [])
    .map(entry => convertHookEntry(entry, pluginRoot))
    .filter(Boolean);

  if (stopHooks.length > 0) {
    lines.push("    'session.idle': async (input, output) => {");
    lines.push('');

    for (const hook of stopHooks) {
      lines.push(`      // ${hook.description || hook.id}`);
      lines.push(`      try {`);
      lines.push(`        const { execSync } = require('child_process');`);
      lines.push(`        const command = \`${hook.hooks[0].command.replace(/`/g, '\\`')}\`;`);
      lines.push(`        execSync(command, { timeout: ${hook.hooks[0].timeout * 1000}, cwd: directory });`);
      lines.push(`      } catch (error) {`);
      lines.push(`        // Hook failed, continue execution`);
      lines.push(`      }`);
      lines.push('');
    }

    lines.push('    },');
  }

  lines.push('  };');
  lines.push('};');

  return lines.join('\n');
}

/**
 * 转换 hooks 插件（供 install-platform.js 调用）
 */
function convertHooksPlugin(root, opencodeHome) {
  const pluginDir = path.join(opencodeHome, 'plugins', 'team-skills-platform');

  // 读取 hooks 配置
  const hooksDir = path.join(root, 'hooks');
  const hooksConfig = readHooksConfig(hooksDir);

  // 生成插件代码
  const pluginCode = generatePluginCode(hooksConfig, pluginDir);

  // 写入插件文件
  const pluginsDir = path.join(opencodeHome, 'plugins');
  fs.mkdirSync(pluginsDir, { recursive: true });
  const pluginPath = path.join(pluginsDir, 'tsp-hooks.js');
  fs.writeFileSync(pluginPath, pluginCode, 'utf8');

  console.log(`Generated OpenCode hooks plugin at ${pluginPath}`);
  console.log(`   Hooks converted: ${Object.values(hooksConfig.hooks).flat().length}`);
}

/**
 * 主函数
 */
function main() {
  const root = path.join(__dirname, '../../..');
  const opencodeHome = process.argv[2] || path.join(require('os').homedir(), '.config', 'opencode');

  console.log('Converting hooks for OpenCode...');
  console.log(`Root: ${root}`);
  console.log(`Target: ${opencodeHome}`);

  convertHooksPlugin(root, opencodeHome);

  console.log('✅ Hooks conversion completed');
}

// 导出函数供其他脚本使用
module.exports = {
  convertHookEntry,
  generatePluginCode,
  readHooksConfig,
  convertHooksPlugin,
  EVENT_MAPPING,
  TOOL_MAPPING,
};

// 如果直接运行此脚本
if (require.main === module) {
  try {
    main();
  } catch (error) {
    console.error('Error converting hooks:', error.message);
    process.exitCode = 1;
  }
}
